### ISSUE TITLE
_site folder does affect website

### ISSUE THREAD

**Issue by beny2000** [vaughanline/vaughanline.github.io#1]
was upload after first commit from original site files, seems to not change/affect the main site, not sure what to do

**Comment by beny2000** [comment]
tried removing _site from ititgnore

**Comment by beny2000** [comment]
index.html file does affect site  but does not refresh itself every new object needs to hard coded (not ideal)

**Comment by mrparkonline** [comment]
Been a busy personal weekend.
However, I finally ended up getting jekyll setup on my machine.
- Will be testing how things work soon.

- Mr. Park
